# this module is needed by `driver.py` for the `generate_electron_position_vector` function

e_list = [
    {'symbol': 'H', 'atomic_number': 1, 'period': 1},
    {'symbol': 'He', 'atomic_number': 2, 'period': 1},
    {'symbol': 'Li', 'atomic_number': 3, 'period': 2},
    {'symbol': 'Be', 'atomic_number': 4, 'period': 2},
    {'symbol': 'B', 'atomic_number': 5, 'period': 2},
    {'symbol': 'C', 'atomic_number': 6, 'period': 2},
    {'symbol': 'N', 'atomic_number': 7, 'period': 2},
    {'symbol': 'O', 'atomic_number': 8, 'period': 2},
    {'symbol': 'F', 'atomic_number': 9, 'period': 2},
    {'symbol': 'Ne', 'atomic_number': 10, 'period': 2},
    {'symbol': 'Na', 'atomic_number': 11, 'period': 3},
    {'symbol': 'Mg', 'atomic_number': 12, 'period': 3},
    {'symbol': 'Al', 'atomic_number': 13, 'period': 3},
    {'symbol': 'Si', 'atomic_number': 14, 'period': 3},
    {'symbol': 'P', 'atomic_number': 15, 'period': 3},
    {'symbol': 'S', 'atomic_number': 16, 'period': 3},
    {'symbol': 'Cl', 'atomic_number': 17, 'period': 3},
    {'symbol': 'Ar', 'atomic_number': 18, 'period': 3},
    {'symbol': 'K', 'atomic_number': 19, 'period': 4},
    {'symbol': 'Ca', 'atomic_number': 20, 'period': 4},
    {'symbol': 'Sc', 'atomic_number': 21, 'period': 4, 'spin': 1},
    {'symbol': 'Ti', 'atomic_number': 22, 'period': 4, 'spin': 2},
    {'symbol': 'V', 'atomic_number': 23, 'period': 4, 'spin': 3},
    {'symbol': 'Cr', 'atomic_number': 24, 'period': 4, 'spin': 6},
    {'symbol': 'Mn', 'atomic_number': 25, 'period': 4, 'spin': 5},
    {'symbol': 'Fe', 'atomic_number': 26, 'period': 4, 'spin': 4},
    {'symbol': 'Co', 'atomic_number': 27, 'period': 4, 'spin': 3},
    {'symbol': 'Ni', 'atomic_number': 28, 'period': 4, 'spin': 2},
    {'symbol': 'Cu', 'atomic_number': 29, 'period': 4, 'spin': 1},
    {'symbol': 'Zn', 'atomic_number': 30, 'period': 4, 'spin': 0},
    {'symbol': 'Ga', 'atomic_number': 31, 'period': 4},
    {'symbol': 'Ge', 'atomic_number': 32, 'period': 4},
    {'symbol': 'As', 'atomic_number': 33, 'period': 4},
    {'symbol': 'Se', 'atomic_number': 34, 'period': 4},
    {'symbol': 'Br', 'atomic_number': 35, 'period': 4},
    {'symbol': 'Kr', 'atomic_number': 36, 'period': 4},
    {'symbol': 'Rb', 'atomic_number': 37, 'period': 5},
    {'symbol': 'Sr', 'atomic_number': 38, 'period': 5},
    {'symbol': 'Y', 'atomic_number': 39, 'period': 5, 'spin': 1},
    {'symbol': 'Zr', 'atomic_number': 40, 'period': 5, 'spin': 2},
    {'symbol': 'Nb', 'atomic_number': 41, 'period': 5, 'spin': 5},
    {'symbol': 'Mo', 'atomic_number': 42, 'period': 5, 'spin': 6},
    {'symbol': 'Tc', 'atomic_number': 43, 'period': 5, 'spin': 5},
    {'symbol': 'Ru', 'atomic_number': 44, 'period': 5, 'spin': 4},
    {'symbol': 'Rh', 'atomic_number': 45, 'period': 5, 'spin': 3},
    {'symbol': 'Pd', 'atomic_number': 46, 'period': 5, 'spin': 0},
    {'symbol': 'Ag', 'atomic_number': 47, 'period': 5, 'spin': 1},
    {'symbol': 'Cd', 'atomic_number': 48, 'period': 5, 'spin': 0},
    {'symbol': 'In', 'atomic_number': 49, 'period': 5},
    {'symbol': 'Sn', 'atomic_number': 50, 'period': 5},
    {'symbol': 'Sb', 'atomic_number': 51, 'period': 5},
    {'symbol': 'Te', 'atomic_number': 52, 'period': 5},
    {'symbol': 'I', 'atomic_number': 53, 'period': 5},
    {'symbol': 'Xe', 'atomic_number': 54, 'period': 5},
    {'symbol': 'Cs', 'atomic_number': 55, 'period': 6},
    {'symbol': 'Ba', 'atomic_number': 56, 'period': 6},
    {'symbol': 'La', 'atomic_number': 57, 'period': 6},
    {'symbol': 'Ce', 'atomic_number': 58, 'period': 6},
    {'symbol': 'Pr', 'atomic_number': 59, 'period': 6},
    {'symbol': 'Nd', 'atomic_number': 60, 'period': 6},
    {'symbol': 'Pm', 'atomic_number': 61, 'period': 6},
    {'symbol': 'Sm', 'atomic_number': 62, 'period': 6},
    {'symbol': 'Eu', 'atomic_number': 63, 'period': 6},
    {'symbol': 'Gd', 'atomic_number': 64, 'period': 6},
    {'symbol': 'Tb', 'atomic_number': 65, 'period': 6},
    {'symbol': 'Dy', 'atomic_number': 66, 'period': 6},
    {'symbol': 'Ho', 'atomic_number': 67, 'period': 6},
    {'symbol': 'Er', 'atomic_number': 68, 'period': 6},
    {'symbol': 'Tm', 'atomic_number': 69, 'period': 6},
    {'symbol': 'Yb', 'atomic_number': 70, 'period': 6},
    {'symbol': 'Lu', 'atomic_number': 71, 'period': 6},
    {'symbol': 'Hf', 'atomic_number': 72, 'period': 6},
    {'symbol': 'Ta', 'atomic_number': 73, 'period': 6},
    {'symbol': 'W', 'atomic_number': 74, 'period': 6},
    {'symbol': 'Re', 'atomic_number': 75, 'period': 6},
    {'symbol': 'Os', 'atomic_number': 76, 'period': 6},
    {'symbol': 'Ir', 'atomic_number': 77, 'period': 6},
    {'symbol': 'Pt', 'atomic_number': 78, 'period': 6},
    {'symbol': 'Au', 'atomic_number': 79, 'period': 6},
    {'symbol': 'Hg', 'atomic_number': 80, 'period': 6},
    {'symbol': 'Tl', 'atomic_number': 81, 'period': 6},
    {'symbol': 'Pb', 'atomic_number': 82, 'period': 6},
    {'symbol': 'Bi', 'atomic_number': 83, 'period': 6},
    {'symbol': 'Po', 'atomic_number': 84, 'period': 6},
    {'symbol': 'At', 'atomic_number': 85, 'period': 6},
    {'symbol': 'Rn', 'atomic_number': 86, 'period': 6},
    {'symbol': 'Fr', 'atomic_number': 87, 'period': 7},
    {'symbol': 'Ra', 'atomic_number': 88, 'period': 7},
    {'symbol': 'Ac', 'atomic_number': 89, 'period': 7},
    {'symbol': 'Th', 'atomic_number': 90, 'period': 7},
    {'symbol': 'Pa', 'atomic_number': 91, 'period': 7},
    {'symbol': 'U', 'atomic_number': 92, 'period': 7},
    {'symbol': 'Np', 'atomic_number': 93, 'period': 7},
    {'symbol': 'Pu', 'atomic_number': 94, 'period': 7},
    {'symbol': 'Am', 'atomic_number': 95, 'period': 7},
    {'symbol': 'Cm', 'atomic_number': 96, 'period': 7},
    {'symbol': 'Bk', 'atomic_number': 97, 'period': 7},
    {'symbol': 'Cf', 'atomic_number': 98, 'period': 7},
    {'symbol': 'Es', 'atomic_number': 99, 'period': 7},
    {'symbol': 'Fm', 'atomic_number': 100, 'period': 7},
    {'symbol': 'Md', 'atomic_number': 101, 'period': 7},
    {'symbol': 'No', 'atomic_number': 102, 'period': 7},
    {'symbol': 'Lr', 'atomic_number': 103, 'period': 7},
    {'symbol': 'Rf', 'atomic_number': 104, 'period': 7},
    {'symbol': 'Db', 'atomic_number': 105, 'period': 7},
    {'symbol': 'Sg', 'atomic_number': 106, 'period': 7},
    {'symbol': 'Bh', 'atomic_number': 107, 'period': 7},
    {'symbol': 'Hs', 'atomic_number': 108, 'period': 7},
    {'symbol': 'Mt', 'atomic_number': 109, 'period': 7},
    {'symbol': 'Ds', 'atomic_number': 110, 'period': 7},
    {'symbol': 'Rg', 'atomic_number': 111, 'period': 7},
    {'symbol': 'Cn', 'atomic_number': 112, 'period': 7},
    {'symbol': 'Nh', 'atomic_number': 113, 'period': 7},
    {'symbol': 'Fl', 'atomic_number': 114, 'period': 7},
    {'symbol': 'Mc', 'atomic_number': 115, 'period': 7},
    {'symbol': 'Lv', 'atomic_number': 116, 'period': 7},
    {'symbol': 'Ts', 'atomic_number': 117, 'period': 7},
    {'symbol': 'Og', 'atomic_number': 118, 'period': 7},
]